name: openssl stable for windows

on: 
  workflow_dispatch:

jobs:
  Builds:
    uses: ./.github/workflows/test.yml
    with:
      major: 3
      minor: 5
      patch: 3
      REPO_BRANCH: openssl-3.5.3
