name: openssl latest for windows

on: 
  workflow_dispatch:

jobs:
  Builds:
    uses: ./.github/workflows/test.yml
    with:
      major: 3
      minor: 6
      patch: 0-dev
      REPO_BRANCH: master
      PRE: true
