name: openssl latest for windows

on: 
  workflow_dispatch:

jobs:
  Builds:
    uses: ./.github/workflows/test.yml
    with:
      major: 3
      minor: 3
      patch: 4-dev
      REPO_BRANCH: openssl-3.3
